# Site settings
title: Geoffrey Botin - Fullstack web developer
email: geoffrey.botin@gmail.com

description: >
  Passionate about new technologies, Ruby on Rails developer since 5 years,
  I had several times the opportunity to work in the world of startups.
  Eager for new experiences and willing to value my skills,
  I'd like to help you build your things.

url: http://gbotin.github.io

twitter_username: geoffrey_botin
github_username:  gbotin
linkedin_username:  gbotin
skype_username: geoffrey.botin

email: geoffrey.botin@gmail.com
phone: +33 6 32 35 34 80

markdown: kramdown
timezone: Europe/Paris

port: 3000
host: localhost

source: ./src

collections:
  - portfolio
  - experiences

exclude:
  - assets/dev
