# Site settings
title: Geoffrey Botin - Ruby on Rails developer / DevOps
email: geoffrey.botin@gmail.com

description: >
  Passionate about new technologies, Ruby on Rails developer since 5 years,
  I had several times the opportunity to work in the world of startups.
  Eager for new experiences and willing to value my skills,
  I now offer my services as a freelance to help you with your projects.

url: "http://gbotin.github.io"

twitter_username: geoffrey_botin
github_username:  gbotin

markdown: kramdown
timezone: Europe/Paris

port: 3000
host: localhost

sass:
  sass_dir: _sass
  # style: :compressed

exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gruntfile.coffee"

include:
  - .nojekyll
